# Generated by Django 4.1.7 on 2023-03-02 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='imageEvent',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
